# Generated by Django 5.0.3 on 2024-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('img1', models.ImageField(upload_to='media/')),
                ('description2', models.TextField()),
                ('img2', models.ImageField(upload_to='media/')),
                ('description3', models.TextField()),
                ('img3', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
